# Azure Static Web Apps

name: Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - task: AzureStaticWebApp@0
        inputs:
          skip_app_build: true
          app_build_command: echo
          app_location: "/"
          api_location: "api"
          output_location: "build"
          azure_static_web_apps_api_token: "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}"
